### ISSUE TITLE
Link tag is not created correctly.

### ISSUE THREAD

**Issue by chanlito** [visualjerk/quill-magic-url#4]
so using the following:

```js
magicUrl: {
          globalRegularExpression: /(https?:\/\/|www\.|mailto:)[\S]+/g,
          urlRegularExpression: /(https?:\/\/[\S]+)|(www.[\S]+)|(mailto:[\S]+)/,
        },
```

if I type `www.google.com` -> when I display the content, when click it appends current url + `www.google.com`
if I type `https://www.google.com` -> it display the link correctly.

Do i miss something? 

BTW Awesome module.

**Comment by visualjerk** [comment]
This behaviour is how regular a-Tags work. `<a href="www.google.com">www.google.com</a>` will always try to open the URL relative to the current site.

However you touch a good point here. URLs should be normalized, so that typing `www.google.com` will result in `<a href="http://www.google.com">www.google.com</a>`.

This feature is added with #5 

Please update to the latest version (1.0.0).

**Comment by paolavness** [comment]
Yes it is totally default behavior and totally great to normalize it, thank you for the quick fix.
