### ISSUE TITLE
Version 1.0.0 breaking UglifyJs

### ISSUE THREAD

**Issue by paolavness** [visualjerk/quill-magic-url#7]
Latest version (1.0.0) is breaking uglify - 
```
ERROR in bundle.3ea945f01cedf37be812.js from UglifyJs
Unexpected token: operator (>) [./node_modules/quill-magic-url/dist/index.js:1
```

Thank you.

**Comment by paolavness** [comment]
Any news on this?

**Comment by paolavness** [comment]
Any news on this? The previous version was working fine so assume its something small.

**Comment by visualjerk** [comment]
Unfortunately this issue seems to need some time to be solved properly. For a fast fix, you can try to replace every arrow function `() =>` in src/index.js with a normal `function ()` and build your own dist/index.js with npm run build.

I will configure webpack to get rid of the issue as soon as I find the time.

**Comment by ycjcl868** [comment]
![image](https://user-images.githubusercontent.com/13595509/43773674-16114d92-9a79-11e8-9dd4-c64db2664ffa.png)

**Comment by visualjerk** [comment]
As there hasn't been any other people running into this issue, I assume it doesn't persist with the current version.
