### ISSUE TITLE
Why are UTM params being stripped away?

### ISSUE THREAD

**Issue by zehawki** [visualjerk/quill-magic-url#71]
I've been very puzzled by a recent discovery that UTM params from links are being stripped away, and after debugging I've narrowed it down to this extension.

Eg using the demo: https://visualjerk.github.io/quill-magic-url/. If I paste the following: `https://github.com/visualjerk/quill-magic-url/issues?ut_source=1&ut_campaign=2&utm_medium=3`

The actual link becomes: `https://github.com/visualjerk/quill-magic-url/issues?ut_campaign=2&ut_source=1`

![image](https://user-images.githubusercontent.com/8095144/160713112-c5382b4f-be1c-4b42-a0f5-d36f62a08a9e.png)

Any param with "utm_" is stripped away. Another example. Pasting this: `https://github.com/visualjerk/quill-magic-url/issues?utm_source=1&utm_campaign=2&utm_medium=3`

turns into: `https://github.com/visualjerk/quill-magic-url/issues`

![image](https://user-images.githubusercontent.com/8095144/160713247-729fda76-bf1b-4ac3-933d-f469ae697cee.png)

**Comment by visualjerk** [comment]
Hey! Thanks for submitting this issue. I was initially thinking about some strange behavior with the underlying package `normalize-url`. Turns out it is a feature of this package. By default all query params starting with `utm_` are stripped:

https://github.com/sindresorhus/normalize-url#removequeryparameters

If you like to disable this feature, you can do so by providing custom normalizeUrlOptions:

```js
magicUrl: {
  normalizeUrlOptions: {
    stripWWW: false,
    removeQueryParameters: false
  }
}
```

**Comment by zehawki** [comment]
Thank you for this update. What a strangely opinionated library normalize-url is.
